version: 1.0.{build}
nuget:
  account_feed: true
  project_feed: true
build_script:
- gem install bundle
- bundle
- rake package
test: off
artifacts:
- path: '*.nupkg'
deploy:
- provider: NuGet
  server: 
  api_key:
    secure: fGNwXOtebe3kxu5SrB90CrbaCxVxuzuCQh3Ipcc0G/3cutoNZf7d7G6AaQ4fRv2l
  skip_symbols: true
  artifact: '*.nupkg'